services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"

  book-service:
    build: ./book-service
    ports:
      - "8082:8082"

  loan-service:
    build: ./loan-service
    ports:
      - "8083:8083"
    environment:
      - USER_SERVICE_URL=http://user-service:8081
      - BOOK_SERVICE_URL=http://book-service:8082

  nginx:
    build: ./nginx
    ports:
      - "80:80"
