version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: smart-library-user-service
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
      - PORT=8081
    volumes:
      - user-data:/app/data
    networks:
      - library-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  book-service:
    build:
      context: ./book-service
      dockerfile: Dockerfile
    container_name: smart-library-book-service
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=production
      - PORT=8082
    volumes:
      - book-data:/app/data
    networks:
      - library-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8082/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  loan-service:
    build:
      context: ./loan-service
      dockerfile: Dockerfile
    container_name: smart-library-loan-service
    ports:
      - "8083:8083"
    environment:
      - NODE_ENV=production
      - PORT=8083
      - USER_SERVICE_URL=http://user-service:8081
      - BOOK_SERVICE_URL=http://book-service:8082
    volumes:
      - loan-data:/app/data
    networks:
      - library-network
    restart: unless-stopped
    depends_on:
      user-service:
        condition: service_healthy
      book-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8083/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: smart-library-nginx
    ports:
      - "80:80"
    networks:
      - library-network
    restart: unless-stopped
    depends_on:
      user-service:
        condition: service_healthy
      book-service:
        condition: service_healthy
      loan-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  user-data:
    driver: local
  book-data:
    driver: local
  loan-data:
    driver: local

networks:
  library-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
